[project]
name = "talent-value-forecast"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "matplotlib>=3.10.3",
    "pip>=25.1.1",
    "seaborn>=0.13.2",
]
